-- This file was generated by				
-- Qfsm Version 0.54					
-- (C) Stefan Duffner, Rainer Strobel			


-- Inputs:   Entrada
-- State/Output Saida
-- S0           0     
-- S1           0     
-- S2           0     
-- S3           0     
-- S4           1     

LIBRARY IEEE;

USE IEEE.std_logic_1164.ALL;

ENTITY Detector_0111 IS
  PORT (clk: IN std_ulogic;
        rst_n: IN std_ulogic;
        Entrada: IN std_ulogic;
        Saida: OUT std_ulogic);
END Detector_0111;

ARCHITECTURE behave OF Detector_0111 IS

TYPE state_type IS (S0, S1, S2, S3, S4);
SIGNAL next_state, current_state : state_type;

BEGIN
  state_register: PROCESS (rst_n, clk)
  BEGIN
    IF rst_n='0' THEN
      current_state <= S0;
    ELSIF rising_edge(clk) THEN
      current_state <= next_state;
    END IF;
  END PROCESS;

  next_state_and_output_logic: PROCESS (current_state, Entrada)
    VARIABLE temp_input : std_ulogic_vector(0 DOWNTO 0);
    VARIABLE temp_output : std_ulogic_vector(0 DOWNTO 0);
  BEGIN
    temp_input(0) := Entrada;
    CASE current_state IS
      WHEN S0 => temp_output := "0";
        IF temp_input="0" THEN
          next_state <= S1;
        ELSIF temp_input="1" THEN
          next_state <= S0;
        ELSE
          next_state <= current_state;
        END IF;
      WHEN S1 => temp_output := "0";
        IF temp_input="0" THEN
          next_state <= S1;
        ELSIF temp_input="1" THEN
          next_state <= S2;
        ELSE
          next_state <= current_state;
        END IF;
      WHEN S2 => temp_output := "0";
        IF temp_input="1" THEN
          next_state <= S3;
        ELSIF temp_input="0" THEN
          next_state <= S1;
        ELSE
          next_state <= current_state;
        END IF;
      WHEN S3 => temp_output := "0";
        IF temp_input="1" THEN
          next_state <= S4;
        ELSIF temp_input="0" THEN
          next_state <= S1;
        ELSE
          next_state <= current_state;
        END IF;
      WHEN S4 => temp_output := "1";
        IF temp_input="0" THEN
          next_state <= S1;
        ELSIF temp_input="1" THEN
          next_state <= S4;
        ELSE
          next_state <= current_state;
        END IF;
      WHEN OTHERS => temp_output := (OTHERS =>'X');
      next_state <= S0;
    END CASE;
    Saida <= temp_output(0);
  END PROCESS;

END behave;
