-- This file was generated by				
-- Qfsm Version 0.54					
-- (C) Stefan Duffner, Rainer Strobel			


-- Inputs:   Entrada
-- State/Output Saida
-- S0           0     
-- S1           0     
-- S2           0     
-- S3           0     
-- S4           1   

LIBRARY IEEE;

USE IEEE.std_logic_1164.ALL;

ENTITY Detector_0111_tb IS
END Detector_0111_tb;

ARCHITECTURE behave OF Detector_0111_tb IS
component Detector_0111 is
	port (	clk: IN std_ulogic;
        	rst_n: IN std_ulogic;
        	Entrada: IN std_ulogic;
        	Saida: OUT std_ulogic);
END component;

-- Inputs
SIGNAL clk, rst_n, Entrada: std_logic;

-- Outputs
SIGNAL Saida : std_logic;

-- Definitions
constant cin_period : time := 10 ns;


BEGIN

-- Instantiate the Unit Under Test (UUT)
uut: Detector_0111 port map (
	clk => clk,
	rst_n => rst_n,
	Entrada => Entrada,
	Saida => Saida
);

-- Clock process
Cin_process :process
begin
	clk <= '0';
	wait for Cin_period/2;
	clk <='1';
	wait for Cin_period/2;
	
end process;

-- Stimulus process
stim_proc: process
begin
	rst_n <= '0';
	wait for cin_period;
	Entrada <= '0';
	wait for cin_period;
	Entrada <= '1';
	wait for cin_period;
	Entrada <= '1';
	wait for cin_period;
	Entrada <= '1';
	wait for cin_period;
	Entrada <= '0';
	wait;

end process;

END behave;